Add MatchMethod enum
IABTechLab/adcom-proto pull request #20
Opened 2024-10-07 11:55 UTC by Symbols-max

[https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#3227---object-eid-](https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#3227---object-eid-)

2024-10-07 12:10 UTC, dmytro-babichev requested changes

2024-10-07 13:32 UTC, dmytro-babichev approved these changes

2024-10-15 16:39 UTC, simontrasler commented on proto/com/iabtechlab/adcom/v1/enums/enums.proto
> +
Nit: extra line.

2024-10-15 16:46 UTC, simontrasler approved these changes

2024-10-16 14:24 UTC, merged